### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by andrew-boyarshin** [STALKER2010/Butterfly#1]
- [ ] Butterfly common - check for memory leaks
- [ ] Butterfly thread pool - Ability to change number of threads
- [ ] Demo - add delay tests
- [ ] Demo - fix orientation change handling
- [ ] Demo - write more debug messages to log
